### ISSUE TITLE
Support running a Gradle Task from right click on a subproject in IDE

### ISSUE THREAD

**Issue by ZakTaccardi** [dropbox/focus#20]
Our team recently added the [Focus](https://dropbox.tech/mobile/introducing-focus-a-new-open-source-gradle-plugin) gradle plugin, which adds tasks like `:subproject:focus`.

I'd love support in the IDE to be able to right click and run specific Gradle tasks from the right-click on subproject context menu.

For example, I have a subproject: `:util:app-in-foreground-observer`. I would like to be able to right click on the subproject from the left side project menu in Android Studio and see a context menu with:

```
Run Gradle Task `:util:app-in-foreground-observer:focus`
```

While this is a useful feature for Focus, it makes sense that the IDE as a whole supports executing generating Gradle tasks from the context of a subproject, so I filed https://youtrack.jetbrains.com/issue/IDEA-291803 as well

**Comment by DevSrSouza** [comment]
I have being working on a plugin for Focus, and it does have this feature.
https://github.com/DevSrSouza/dropbox-focus-intellij-plugin/

**Comment by rharter** [comment]
Since the IDEA plugin to support this has been released, I'm going to close this. Thanks, @DevSrSouza!
