### ISSUE TITLE
Generated focus.settings.gradle doesn't respect includeBuild statements

### ISSUE THREAD

**Issue by ConstOrVar** [dropbox/focus#24]
In our project s_ettings.gradle_ we use `includeBuild` statement to add in classpath separate project. 
Focus plugin generates _focus.settings.gradle_ without that statement, that's why **included** project is missing and project configuration become broken.

For example:
original settings.gradle
```
includeBuild("path_to_project")
include ':app'
``` 

generated settings.gradle
```
include ':app'
```

Need to point out that **included** project is not directly used in dependencies section of any subproject. It only contains gradle scripts that is applied at each subprojects.

As workaround, I'm using `project.tasks.findByName("createFocusSettings").finalizedBy(myTask)` to intercept in settings creation process and append in file missing statements. May be you'll provide special configuration property in focus's extension, to allow edit generated settings file?

**Comment by rharter** [comment]
Are you talking about your `settings-all.gradle` file? Simply leave the `includeBuild` statement in your main settings file, and only move `include` statements to your `settings-all.gradle` file.

The readme says to move your `include` statements to `settings-all.gradle`, not everything. Stuff that should always happen whether in focus mode or not, like your `includeBuild` statements should stay in the main settings file. 

> Move all non-required `include` statements into `settings-all.gradle`. Projects that are always included can remain in your main `settings.gradle` file.

**Comment by ConstOrVar** [comment]
@rharter thanks! I've missed that point.
