### ISSUE TITLE
Consider Gradle Kotlin DSL gradle.kts files

### ISSUE THREAD

**Issue by stephanepechard** [dropbox/focus#32]
Hello,
Trying to use this plugin with a Kotlin Multiplatform project, it does not work, as it looks for a hard-named `settings-all.gradle`, which is not compatible with `.kts` files.
Is it possible to make it compatible with [Gradle's Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html)?

Thanks,

**Comment by rharter** [comment]
You can find the instructions in the [Readme](https://github.com/dropbox/focus#setup) detailing using the `allSettingsFileName` to override the name of the settings file it looks for. If that doesn't work for you feel free to open another issue.

**Comment by stephanepechard** [comment]
Thanks for the answer Ryan, I thought it was the file format and not just the naming. Sorry for the disturbance.
